INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME, PHONE_NUMBER) VALUES (1, 'Sam Jones', 254722);
INSERT INTO AUTHOR (AUTHOR_ID,AUTHOR_NAME, PHONE_NUMBER) VALUES (2, 'Jane Jill', 254733);
INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME, PHONE_NUMBER) VALUES (3, 'John Smith', 254232);
INSERT INTO AUTHOR (AUTHOR_ID,AUTHOR_NAME, PHONE_NUMBER) VALUES (4, 'Mike Kimani', 254323);
